### ISSUE TITLE
Are there something to demonstrate how to use it?

### ISSUE THREAD

**Issue by xyzwps** [didi/go-spring#5]

**Comment by llitfkitfk** [comment]
https://github.com/go-spring

**Comment by lvan100** [comment]
赞楼上！由于种种原因，还有其他项目不能放在这里，所以新开了一个仓库，里面有一些专门的项目来展示go-spring 的用法，未来也会增加更多的单元测试，相互配合。
https://github.com/go-spring/go-spring-demo
https://github.com/go-spring/go-spring-boot-demo
