### ISSUE TITLE
关于jdbc命名问题

### ISSUE THREAD

**Issue by ccqy66** [didi/go-spring#8]
JDBC 为Java Database Connectivity的缩写，既然是属于golang的框架，起这个名字感觉有些欠妥

**Comment by llitfkitfk** [comment]
gdbc🤣

**Comment by lvan100** [comment]
恩，这个现在还是实验性的模块，后面可能会去掉，我现在考虑优先实现 ORM 框架，我们内部也已经统一到 gorm 了，其他的数据库现在我还没发现更好的，如果有更好的可以推荐推荐。
go-spring 目前的重点是集成现有的成熟项目，而不是自己搞一套。如果社区已经有了很多同领域的项目，可以考虑实现一个抽象层，将这些项目中的 top3 给适配一下，做成开箱即用。
