### ISSUE TITLE
spring-check/spring-check.go中CheckNotNull有些问题

### ISSUE THREAD

**Issue by fpagyu** [didi/go-spring#9]
spring-check/spring-check.go 文件中CheckNotNull函数

使用这个函数局限很大，一不小心就会出问题.

问题看下面链接的文章，应该很清楚:

[链接](https://blog.csdn.net/lanyang123456/article/details/83715090)

举个例子:
```
type A struct {
    Val int
}

func IsNil(i interface{}) bool {
    return i == nil
}

func main() {
    var a A
    var pa *A

    // fmt.Println(a == nil)   // error:
    fmt.Println(IsNil(a))      // false
    fmt.Println(pa == nil)   // true
    fmt.Println(IsNil(pa))   // false
}
```
这个结果应该与您预期想要达到的效果是相悖的

如果IsNil函数中的i本身是一个指针类型的对象(像例子中的pa)，那也还好处理,
但如果i本身是非指针类型的对象(比如例子中的a), 我暂时没有想到好的处理方式

**Comment by llitfkitfk** [comment]
```
func isNilValue(value interface{}) bool {
	return (*[2]uintptr)(unsafe.Pointer(&value))[1] == 0
}
```

**Comment by lvan100** [comment]
多谢 @fpagyu 指正，我研究研究，之前没有这方面的了解 👍

**Comment by fpagyu** [comment]
@lvan100 其实在go的reflect包中，有相关功能的实现，
在go1.13之前的版本中中，通过reflect.ValueOf() 得到一个reflect.Value 类型的对象， 这个对象 有一个IsNil的方法，我看了下， 在go1.13中, 这个对象新增加了一个IsZero的方法,这个IsZero应该能够完全满足你的需要。 但具体到有没有必要需要对一个struct类型(不是这个类型的指针)判空，还需要斟酌一下，毕竟零值和null还是不一样的。

**Comment by lvan100** [comment]
现在check模块已经删除了，实现了新的 rpc error 函数，可以更方便更准确的表达check的语意。
